apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pm
  template:
    metadata:
      labels:
        app: pm
    spec:
      containers:
        - name: pm-app
          image: petmanager-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: neon-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: neon-config
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neon-secret
                  key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: pm-service
spec:
  type: LoadBalancer
  selector:
    app: pm
  ports:
    - port: 8080
      targetPort: 8080