spring.application.name=pet_manager
server.port=${PORT:8080}

# Configuración DB Neon
spring.datasource.url=jdbc:postgresql://ep-billowing-bush-adcebu8v-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aTQ9fPtHF8AG

# ** CORRECCIÓN DE ESTABILIDAD: CONFIGURACIÓN HIKARI **
# Ajuste de tiempo de vida máximo para prevenir que el pool intente reutilizar conexiones cerradas por el proveedor de DB
spring.datasource.hikari.max-lifetime=1770000

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración JWT
jwt.secret=qEmcLlOlHDrltceHxu/32UMAay6Z4tdilYqnpTXluGA=
jwt.expirationMs= 3600000

# Configuración de Logging y Debugging
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuración de Transacciones
spring.transaction.default-timeout=30
spring.transaction.rollback-on-commit-failure=true

# Configuración de MVC
spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.media-types.json=application/json

# --- Actuator configuration ---
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Configuración de Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# --- HATEOAS configuration ---
spring.hateoas.use-hal-as-default-json-media-type=true

# --- Notification configuration ---
# Umbral para considerar una venta como de "alto volumen" (en cantidad de productos)
notification.high-volume.threshold=10

# Destinatarios de las notificaciones de alto volumen (separados por coma)
notification.email.recipients=compras@petmanager.com,gerencia@petmanager.com